#!/usr/bin/env node
/**
 * build-seo.js — writes the search-engine and link-preview tags into index.html,
 * and creates robots.txt + sitemap.xml, all from config.js.
 *
 * Why this exists: WhatsApp, Facebook and Google's first pass read the raw HTML and do NOT run
 * JavaScript, so the store name, description and preview photo have to be in index.html itself.
 *
 * Usage (needs Node.js, nothing to install):
 *   1. Edit config.js (siteUrl, seoTitle, seoDescription, photos…)
 *   2. node build-seo.js
 *   3. Deploy. Run it again whenever you change those config values.
 */
"use strict";
var fs = require("fs");
var path = require("path");
var vm = require("vm");

var dir = __dirname;
var sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(dir, "config.js"), "utf8"), sandbox);
var cfg = sandbox.window.STORE_CONFIG;
if (!cfg) { console.error("config.js did not define STORE_CONFIG."); process.exit(1); }

function esc(s) {
  return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

var full = (cfg.storeName + (cfg.storeNameAccent ? " " + cfg.storeNameAccent : "")).trim();
var title = cfg.seoTitle || full;
var desc = cfg.seoDescription || cfg.heroSubtitle || "";
var site = (cfg.siteUrl || "").trim().replace(/\/+$/, "");
var home = site ? site + "/" : "";

if (!site) {
  console.warn("! siteUrl is empty in config.js — skipping canonical link, sitemap and the link-preview photo.\n" +
               "  Set siteUrl to your live address (e.g. \"https://mrevans.com.ng\") and run this again.");
}

// Preview photo: seoImage → first hero image → first product photo
function imageUrl(file) {
  if (!file) return "";
  if (/^https?:\/\//i.test(file)) return file;
  var folder = cfg.imageFolder == null ? "images/" : cfg.imageFolder;
  if (folder && !/\/$/.test(folder)) folder += "/";
  var rel = /^\//.test(file) ? file.replace(/^\//, "") : folder + file.replace(/^\.?\//, "");
  return site ? site + "/" + rel : "";
}
var firstProduct = (cfg.products || []).filter(function (p) { return p.image; })[0];
var ogImage = imageUrl(cfg.seoImage || (cfg.heroImages && cfg.heroImages[0]) || (firstProduct && firstProduct.image));

var ld = {
  "@context": "https://schema.org",
  "@type": cfg.businessType || "Store",
  name: full,
  description: desc,
  telephone: cfg.phoneDisplay,
  address: { "@type": "PostalAddress", streetAddress: cfg.address, addressCountry: "NG" }
};
if (home) ld.url = home;
if (ogImage) ld.image = ogImage;
if (cfg.priceRange) ld.priceRange = cfg.priceRange;
if (cfg.openingHours && cfg.openingHours.length) ld.openingHours = cfg.openingHours;
var same = [cfg.socials && cfg.socials.instagram, cfg.socials && cfg.socials.facebook].filter(Boolean);
if (same.length) ld.sameAs = same;

var lines = [];
lines.push("<title>" + esc(title) + "</title>");
if (desc) lines.push('<meta name="description" content="' + esc(desc) + '">');
if (home) lines.push('<link rel="canonical" href="' + esc(home) + '">');
lines.push('<meta property="og:type" content="website">');
lines.push('<meta property="og:site_name" content="' + esc(full) + '">');
lines.push('<meta property="og:title" content="' + esc(title) + '">');
if (desc) lines.push('<meta property="og:description" content="' + esc(desc) + '">');
if (home) lines.push('<meta property="og:url" content="' + esc(home) + '">');
if (ogImage) lines.push('<meta property="og:image" content="' + esc(ogImage) + '">');
lines.push('<meta name="twitter:card" content="' + (ogImage ? "summary_large_image" : "summary") + '">');
lines.push('<meta name="twitter:title" content="' + esc(title) + '">');
if (desc) lines.push('<meta name="twitter:description" content="' + esc(desc) + '">');
if (ogImage) lines.push('<meta name="twitter:image" content="' + esc(ogImage) + '">');
lines.push('<script type="application/ld+json" id="ld-json">' + JSON.stringify(ld).replace(/</g, "\\u003c") + "</script>");

var block = "<!-- SEO:START (generated by build-seo.js — edit config.js, then run: node build-seo.js) -->\n" +
  lines.join("\n") + "\n<!-- SEO:END -->";

var htmlPath = path.join(dir, "index.html");
var html = fs.readFileSync(htmlPath, "utf8");
var re = /<!-- SEO:START[\s\S]*?<!-- SEO:END -->/;
if (!re.test(html)) { console.error("Could not find the SEO:START / SEO:END markers in index.html."); process.exit(1); }
fs.writeFileSync(htmlPath, html.replace(re, function () { return block; }));

fs.writeFileSync(path.join(dir, "robots.txt"),
  "User-agent: *\nAllow: /\n" + (home ? "Sitemap: " + home + "sitemap.xml\n" : ""));
if (home) {
  fs.writeFileSync(path.join(dir, "sitemap.xml"),
    '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    "  <url><loc>" + esc(home) + "</loc><lastmod>" + new Date().toISOString().slice(0, 10) + "</lastmod></url>\n</urlset>\n");
} else if (fs.existsSync(path.join(dir, "sitemap.xml"))) {
  fs.unlinkSync(path.join(dir, "sitemap.xml"));
}

console.log("SEO tags written to index.html" + (home ? ", robots.txt and sitemap.xml created." : " (robots.txt created; no sitemap until siteUrl is set)."));
if (!ogImage && site) console.warn("! No preview photo found — add a product image or set seoImage in config.js.");
